on: pull_request
name: Tests / test-org-mirror
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
    - name: Mirror Github to Gitee
      uses: ./.
      with:
        src: github/hub-mirror-action
        dst: gitee/yikunkero
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        src_account_type: org 
        dst_account_type: user
        # Only sync normal repo
        black_list: 'test'
        white_list: 'normal,test,empty'
        force_update: true
        debug: true
