on: push
name: Tests / test-user-mirror (cached)
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Get time
      id: info
      uses: actions/github-script@v3.0.0
      with:
        result-encoding: string
        script: |
          return new Date(Date.now()).toISOString().replace(/[^0-9]/g, "");

    - name: Cache src repos
      uses: actions/cache@v1
      id: cache
      with:
        path: ${{ github.workspace }}/hub-mirror-cache
        key: ${{ runner.os }}-yikun-repos-cache-${{ steps.info.outputs.time }}
        restore-keys: ${{ runner.os }}-yikun-repos-cache-

    - name: Mirror Github to Gitee with white list and cache
      uses: ./.
      with:
        src: github/Yikun
        dst: gitee/yikunkero
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        cache_path: /github/workspace/hub-mirror-cache
        white_list: 'hub-mirror-action, hexo-migrator-github-issue'
        force_update: true

    - name: Print cache path
      run: |
        ls -la ${{ github.workspace }}/hub-mirror-cache
