on: push
name: Tests / test-org-mirror
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Mirror Github to Gitee
      uses: ./.
      with:
        src: github/kunpengcompute
        dst: gitee/kunpengcompute
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: org
        # Only sync Kunpeng
        black_list: 'KAE'
        white_list: 'KAE,Kunpeng,kunpengcompute.github.io'
        force_update: true
        debug: true
